version: '3.3'
services:
  videoclouddb:
    image: mysql
    networks:
      - videocloud-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=videoclouddb
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - my-db:/var/lib/mysql

  frontend:
    image: ghcr.io/sandervandeurzenstudent/s3-videocloud_frontend:main
    restart: always
    ports: 
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT

  backend: 
    image: ghcr.io/sandervandeurzenstudent/videocloud_backend:main
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - videocloud-network
    depends_on:
      - videoclouddb
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://videoclouddb/videoclouddb",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
# Names our volume
volumes:
  my-db:

networks:
  videocloud-network: 